name: "model"
# network: "alexnet"     # 84/58/45
# network: "vgg11"       # 92/61/45
# network: "vgg16"       # 90/58/55
# network: "resnet18"    # 91/70/95
# network: "resnet34"    # 92/85/80
# network: "resnet101"   # 96/82/80
# network: "densenet121" # 92/76/100
# network: "densenet161" # 92/70/85
# network: "densenet169" # 96/91/90
network: "densenet201"   # 94/94/95
# network: "googlenet"   # 90/73/55
# network: "mobilenet"   # 94/73/60
evaluation_settings:
  - evaluation_kaggle
  - evaluation_real1
  - evaluation_real2

server:
  preview: True

train:
  directory: "data/train"
  preview: false
  make_squared:
    method: "CUTOFF"
  equalization:
    method: "HSV_HIST"
    equalize_s: true
    equalize_v: false

evaluation:
  directory: "data/val_real2"
  print_result: true
  have_qr: true
  preview: false
  make_squared:
    method: "CUTOFF"
  equalization:
    method: "HSV_HIST"
    equalize_s: true
    equalize_v: false

evaluation_kaggle:
  directory: "data/val_kaggle"
  have_qr: false

evaluation_real1:
  directory: "data/val_real1"
  have_qr: true

evaluation_real2:
  directory: "data/val_real2"
  have_qr: true
